apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: {{ .Values.image }}
        ports:
        - containerPort: 8000
        env:
        - name: FASTAPI_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret-{{ .Release.Namespace }}
              key: fastapiJwtSecretKey
        - name: AIRFLOW_APIUSER_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret-{{ .Release.Namespace }}
              key: airflowApiuserUsername
        - name: AIRFLOW_APIUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret-{{ .Release.Namespace }}
              key: airflowApiuserPassword