name: dst_airlines
channels: 
  - defaults
dependencies:
  - python=3.11
  - black
  - flake8
  - ipython
  - isort
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pip
  - python-dotenv
  - scikit-learn
  - tqdm
  - typer
  - requests
  - pip
  - pip:
    - flatten_json
    - -e .
