apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv{{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce  
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: /mnt/data/mongodb-{{ .Release.Namespace }}