apiVersion: v1
kind: PersistentVolume
metadata:
    namespace: {{ .Values.namespace }}
    name: mongodb-pv
spec:
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce  
  hostPath:
    path: /mnt/data/mongodb
  persistentVolumeReclaimPolicy: Retain