apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-{{ .Release.Namespace }}
type: Opaque
data:
  rootpassword: cGFzc3dvcmQxMjM=
  mongodbUsername: YWRtaW4= 
  mongodbPassword: cGFzc3dvcmQxMjM=  
