apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  rootpassword: {{ .Values.mysql.rootPassword | b64enc }}
  password: {{ .Values.mysql.password | b64enc }}
