apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-{{ .Release.Namespace }}
type: Opaque
data:
  rootPassword: cm9vdHBhc3N3b3JkMTIz
  user: dXNlcjEyMw==
  password: cGFzc3dvcmQxMjM=
