apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv-dags
  namespace: airlines
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/airflow/dags