replicaCount: 1

namespace: airlines

image:
  repository: mongo
  tag: "4.4.6"
  pullPolicy: IfNotPresent

mongodbUsername: admin
mongodbPassword: password123
mongodbDatabase: mydatabase

service:
  name: mongo-db
  type: ClusterIP
  port: 27017

persistence:
  size: "1Gi"  
  storageClass: "local-path"  

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
