CREATE USER IF NOT EXISTS 'Gil'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON DST_AIRLINES.* TO 'Gil'@'%';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'Bruno'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON DST_AIRLINES.* TO 'Bruno'@'%';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'Matthieu'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON DST_AIRLINES.* TO 'Matthieu'@'%';
FLUSH PRIVILEGES;