CREATE USER 'Gil'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON DST_AIRLINES.* TO 'Gil'@'%';
FLUSH PRIVILEGES;

CREATE USER 'Bruno'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON DST_AIRLINES.* TO 'Bruno'@'%';
FLUSH PRIVILEGES;

CREATE USER 'Matt'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON DST_AIRLINES.* TO 'Matt'@'%';
FLUSH PRIVILEGES;