# Once completed, move the renamed "secret.yaml" into the "templates" folder

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-{{ .Release.Namespace }}
type: Opaque
data:
  # Add base64-encrypted values here - must be the same, before encryption, as the ones used in the kubernetes/airflow/override.yaml
  fastapiJwtSecretKey: 
  airflowApiuserUsername: 
  airflowApiuserPassword: 